### ISSUE TITLE
3d landmark loss

### ISSUE THREAD

**Issue by heyoon01** [cyj907/unsupervised-detail-layer#13]
Hi! Thanks for sharing such a nice work!
I am trying to train the work with another dataset.
And I noticed the use of landmark3d_loss in the code, which I cannot find in the paper.
I wonder how you got the GT 3D landmark data of CelebA,
and also wonder what the 'segmentation' in the dataset is.

Thanks in advance!

**Comment by heyoon01** [comment]
Got author's reply via e-mail. Share it for any with same question.

From the author: 
The segmentation results can be obtained here.
https://github.com/switchablenorms/CelebAMask-HQ/tree/master/face_parsing

For the landmarks, we trained our own model. But you can obtain results with any SOTA landmark detection model. e.g.  https://github.com/1adrianb/face-alignment
Notice that landmark3d is different from common 2d landmark detection model as the contour of 3d landmark model implies physical face contour, while the contour of 2d landmark detection model indicates face outline (edge information).

**Comment by chen990627** [comment]
> Got author's reply via e-mail. Share it for any with same question.
> 
> From the author: The segmentation results can be obtained here. https://github.com/switchablenorms/CelebAMask-HQ/tree/master/face_parsing
> 
> For the landmarks, we trained our own model. But you can obtain results with any SOTA landmark detection model. e.g. https://github.com/1adrianb/face-alignment Notice that landmark3d is different from common 2d landmark detection model as the contour of 3d landmark model implies physical face contour, while the contour of 2d landmark detection model indicates face outline (edge information).

Hi! Do you have the script for generating the .tfrecords file? Could you provide it?
